const required = [
  'DISCORD_TOKEN',
  'DISCORD_CLIENT_ID',
  'DISCORD_CLIENT_SECRET',
  'TWITCH_CLIENT_ID',
  'TWITCH_CLIENT_SECRET',
];

const missing = required.filter((key) => !process.env[key]);
if (missing.length > 0) {
  console.error(`Missing required environment variables:\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

module.exports = {
  discord: {
    token: process.env.DISCORD_TOKEN,
    clientId: process.env.DISCORD_CLIENT_ID,
    clientSecret: process.env.DISCORD_CLIENT_SECRET,
  },
  twitch: {
    clientId: process.env.TWITCH_CLIENT_ID,
    clientSecret: process.env.TWITCH_CLIENT_SECRET,
  },
  bot: {
    twitchUsername: process.env.BOT_TWITCH_USERNAME || '',
    twitchToken: process.env.BOT_TWITCH_TOKEN || '',
  },
  youtube: {
    apiKey: process.env.YOUTUBE_API_KEY || '',
    botRefreshToken: process.env.YOUTUBE_BOT_REFRESH_TOKEN || '',
    botClientId: process.env.YOUTUBE_BOT_CLIENT_ID || '',
    botClientSecret: process.env.YOUTUBE_BOT_CLIENT_SECRET || '',
  },
  spotify: {
    clientId: process.env.SPOTIFY_CLIENT_ID || '',
    clientSecret: process.env.SPOTIFY_CLIENT_SECRET || '',
  },
  paypal: {
    clientId: process.env.PAYPAL_CLIENT_ID || '',
    clientSecret: process.env.PAYPAL_CLIENT_SECRET || '',
    mode: process.env.PAYPAL_MODE || 'sandbox',
    get baseUrl() {
      return this.mode === 'live'
        ? 'https://api-m.paypal.com'
        : 'https://api-m.sandbox.paypal.com';
    },
  },
  app: {
    url: (process.env.APP_URL || 'http://localhost:3000').replace(/\/$/, ''),
    port: parseInt(process.env.PORT) || 3000,
    sessionSecret: process.env.SESSION_SECRET || 'change-me-in-production',
    adminPassword: process.env.ADMIN_PASSWORD || null,
  },
  intervals: {
    twitchLive: parseInt(process.env.TWITCH_POLL_INTERVAL) || 60_000,
    twitchClips: parseInt(process.env.TWITCH_CLIPS_INTERVAL) || 300_000,
    youtubeFeed: parseInt(process.env.YOUTUBE_FEED_INTERVAL) || 300_000,
    youtubeLive: parseInt(process.env.YOUTUBE_LIVE_INTERVAL) || 120_000,
    subSync: parseInt(process.env.SUB_SYNC_INTERVAL) || 600_000,
    weeklyDigest: parseInt(process.env.WEEKLY_DIGEST_INTERVAL) || 3_600_000,
    instagramFeed: parseInt(process.env.INSTAGRAM_FEED_INTERVAL) || 600_000,
    tiktokFeed: parseInt(process.env.TIKTOK_FEED_INTERVAL) || 600_000,
    twitterFeed: parseInt(process.env.TWITTER_FEED_INTERVAL) || 600_000,
    iracingResults: parseInt(process.env.IRACING_POLL_INTERVAL) || 1_800_000,
  },
  tiers: {
    free: {
      name: 'Free',
      price: 0,
      maxGuilds: -1,
      maxTwitchChannels: -1,
      maxYoutubeChannels: -1,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: true,
      streamSummaries: true,
      goLiveThreads: true,
      webhooks: true,
      whiteLabel: true,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: true,
      instagram: true,
      tiktok: true,
      twitter: true,
      maxSocialAccounts: -1,
      iracing: true,
      maxIracingDrivers: -1,
    },
    starter: {
      name: 'Starter',
      price: 0,
      maxGuilds: -1,
      maxTwitchChannels: -1,
      maxYoutubeChannels: -1,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: true,
      streamSummaries: true,
      goLiveThreads: true,
      webhooks: true,
      whiteLabel: true,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: true,
      instagram: true,
      tiktok: true,
      twitter: true,
      maxSocialAccounts: -1,
      iracing: true,
      maxIracingDrivers: -1,
    },
    pro: {
      name: 'Pro',
      price: 0,
      maxGuilds: -1,
      maxTwitchChannels: -1,
      maxYoutubeChannels: -1,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: true,
      streamSummaries: true,
      goLiveThreads: true,
      webhooks: true,
      whiteLabel: true,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: true,
      instagram: true,
      tiktok: true,
      twitter: true,
      maxSocialAccounts: -1,
      iracing: true,
      maxIracingDrivers: -1,
    },
    enterprise: {
      name: 'Enterprise',
      price: 25,
      maxGuilds: -1,
      maxTwitchChannels: -1,
      maxYoutubeChannels: -1,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: true,
      streamSummaries: true,
      goLiveThreads: true,
      webhooks: true,
      whiteLabel: true,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: true,
      instagram: true,
      tiktok: true,
      twitter: true,
      maxSocialAccounts: -1,
      iracing: true,
      maxIracingDrivers: -1,
    },
  },
};
