const required = [
  'DISCORD_TOKEN',
  'DISCORD_CLIENT_ID',
  'DISCORD_CLIENT_SECRET',
  'TWITCH_CLIENT_ID',
  'TWITCH_CLIENT_SECRET',
];

const missing = required.filter((key) => !process.env[key]);
if (missing.length > 0) {
  console.error(`Missing required environment variables:\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

module.exports = {
  discord: {
    token: process.env.DISCORD_TOKEN,
    clientId: process.env.DISCORD_CLIENT_ID,
    clientSecret: process.env.DISCORD_CLIENT_SECRET,
  },
  twitch: {
    clientId: process.env.TWITCH_CLIENT_ID,
    clientSecret: process.env.TWITCH_CLIENT_SECRET,
  },
  youtube: {
    apiKey: process.env.YOUTUBE_API_KEY || '',
  },
  paypal: {
    clientId: process.env.PAYPAL_CLIENT_ID || '',
    clientSecret: process.env.PAYPAL_CLIENT_SECRET || '',
    mode: process.env.PAYPAL_MODE || 'sandbox',
    get baseUrl() {
      return this.mode === 'live'
        ? 'https://api-m.paypal.com'
        : 'https://api-m.sandbox.paypal.com';
    },
  },
  app: {
    url: (process.env.APP_URL || 'http://localhost:3000').replace(/\/$/, ''),
    port: parseInt(process.env.PORT) || 3000,
    sessionSecret: process.env.SESSION_SECRET || 'change-me-in-production',
    adminPassword: process.env.ADMIN_PASSWORD || null,
  },
  intervals: {
    twitchLive: parseInt(process.env.TWITCH_POLL_INTERVAL) || 60_000,
    twitchClips: parseInt(process.env.TWITCH_CLIPS_INTERVAL) || 300_000,
    youtubeFeed: parseInt(process.env.YOUTUBE_FEED_INTERVAL) || 300_000,
    youtubeLive: parseInt(process.env.YOUTUBE_LIVE_INTERVAL) || 120_000,
    subSync: parseInt(process.env.SUB_SYNC_INTERVAL) || 600_000,
    weeklyDigest: parseInt(process.env.WEEKLY_DIGEST_INTERVAL) || 3_600_000,
  },
  tiers: {
    free: {
      name: 'Free',
      price: 0,
      maxGuilds: 1,
      maxTwitchChannels: 2,
      maxYoutubeChannels: 0,
      twitchLive: true,
      twitchClips: false,
      youtube: false,
      subSync: false,
      welcome: false,
      customEmbedColors: false,
      streamSummaries: false,
      goLiveThreads: false,
      webhooks: false,
      whiteLabel: false,
      delayMinutes: 5,
      recaps: false,
      milestones: false,
      weeklyHighlights: false,
    },
    starter: {
      name: 'Starter',
      price: 5,
      maxGuilds: 3,
      maxTwitchChannels: 10,
      maxYoutubeChannels: 3,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: false,
      streamSummaries: false,
      goLiveThreads: false,
      webhooks: false,
      whiteLabel: false,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: false,
    },
    pro: {
      name: 'Pro',
      price: 10,
      maxGuilds: 10,
      maxTwitchChannels: 50,
      maxYoutubeChannels: 20,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: true,
      streamSummaries: true,
      goLiveThreads: true,
      webhooks: false,
      whiteLabel: false,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: true,
    },
    enterprise: {
      name: 'Enterprise',
      price: 25,
      maxGuilds: -1,
      maxTwitchChannels: -1,
      maxYoutubeChannels: -1,
      twitchLive: true,
      twitchClips: true,
      youtube: true,
      subSync: true,
      welcome: true,
      customEmbedColors: true,
      streamSummaries: true,
      goLiveThreads: true,
      webhooks: true,
      whiteLabel: true,
      delayMinutes: 0,
      recaps: true,
      milestones: true,
      weeklyHighlights: true,
    },
  },
};
